run_scripts()
{
    for script in $1/*; do

        # skip non-readable snippets
        [ -r "$script" ] || continue

        # execute $script in the context of the current shell
        . $script
    done
}

run_scripts .bashrc.d
